export const SPECIALTY_CATEGORY_MAP: Record<string, string[]> = {
  aesthetic_doctor: [
    "non_surgical_face",
    "non_surgical_body",
    "hair_medicine",
    "muscle_tone_ems",
    "iv_therapy",
    "wellness_drainage",
    "longevity",
  ],
  plastic_surgeon: [
    "surgical_face",
    "surgical_body",
    "non_surgical_face",
    "non_surgical_body",
    "hair_medicine",
    "longevity",
  ],
  reconstructive_surgeon: [
    "surgical_face",
    "surgical_body",
    "non_surgical_face",
    "non_surgical_body",
    "longevity",
  ],
  dermatologist: [
    "non_surgical_face",
    "non_surgical_body",
    "hair_medicine",
    "longevity",
    "iv_therapy",
  ],
  general_practitioner: [
    "non_surgical_face",
    "iv_therapy",
    "wellness_drainage",
    "longevity",
    "non_surgical_body",
  ],
  ophthalmologist: ["non_surgical_face", "longevity"],
  oculoplastic_surgeon: ["surgical_face", "non_surgical_face", "longevity"],
  dentist: ["aesthetic_dentistry"],
  maxillofacial_surgeon: [
    "surgical_face",
    "aesthetic_dentistry",
    "non_surgical_face",
  ],
  ent_surgeon: ["surgical_face", "non_surgical_face"],
  orthodontist: ["aesthetic_dentistry"],
  other_specialty: [
    "non_surgical_face",
    "non_surgical_body",
    "hair_medicine",
    "muscle_tone_ems",
    "iv_therapy",
    "wellness_drainage",
    "surgical_face",
    "surgical_body",
    "longevity",
  ],
};