import type { Metadata } from "next";
import { NavPanel } from "@/components/dashboard/NavPanel";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  return <NavPanel>{children}</NavPanel>;
}
