export const DoctorCatalog = {
  specialties: {
    id: "specialties",
    label: "SPECIALTIES (DOCTOR PROFILE ONBOARDING)",
    items: [
      "Aesthetic doctor",
      "Plastic surgeon",
      "Reconstructive surgeon",
      "Dermatologist",
      "General practitioner",
      "Ophthalmologist",
      "Oculoplastic surgeon",
      "Dentist",
      "Maxillofacial surgeon",
      "ENT surgeon",
      "Orthodontist",
      "other specialty",
    ],
  },

  categories: [
    {
      id: "non_surgical_face",
      number: 2,
      label: "NON-SURGICAL FACE",
      items: [
        "Forehead filler",
        "Temple filler",
        "Brow filler",
        "Tear trough filler",
        "Cheek filler",
        "Midface volumization",
        "Non-surgical rhinoplasty (nose filler)",
        "Lip filler",
        "Perioral lines filler",
        "Nasolabial fold filler",
        "Marionette lines filler",
        "Chin filler",
        "Jawline filler",
        "Skin boosters (skin quality injections)",
        "Hyaluronic Acid Filler",
        "Hyaluronidase",
        "Biostimulators / Collagen Stimulators",
        "Skinboosters",
        "Mesotherapy",
        "Polynucleotides / Salmon Sperm",
        "Peptides",
        "BioRePeel",
        "Peeling",
        "Botulinum Toxin",
        "Thread Lifting",
        "Microneedling Radiofrequency",
        "Radiofrequency Without Needles",
        "HIFU",
        "Fractional Laser (Non-ablative)",
        "Fractional Laser (Ablative)",
        "CO2 Laser",
        "Nd:YAG",
        "Laser IPL",
        "BroadBand Light (BBL)",
        "Photorejuvenation",
        "Laser (Picosecond)",
        "LED Therapy",
        "Hydrafacial",
        "Microneedling",
        "Chemical Peel (Medium)",
        "Chemical Peel (Superficial)",
        "PRP Facial",
        "PRF / PRP",
        "Exosome",
        "CaHA",
        "PLLA",
        "PCL",
        "Sofwave",
        "Ultrasound",
        "Microdermabrasion",
        "Skin Analysis / VISIA",
        "PDO Lifting Threads",
        "Permanent Threads",
        "Temporary Threads",
        "Topical RF",
        "RF Microneedling",
        "Skin Quality",
        "Laser/Energy Treatments",
        "Lip Flip",
        "Nose botox",
        "Masseter Botox",
      ],
    },
    {
      id: "non_surgical_body",
      number: 3,
      label: "NON-SURGICAL — BODY",
      items: [
        "Nonsurgical BBL / Liquid BBL",
        "Sculptra buttocks",
        "Endolift",
        "Microneedling RF",
      ],
    },
    {
      id: "aesthetic_dentistry",
      number: 4,
      label: "AESTHETIC DENTISTRY",
      items: [
        "Aesthetic Dentistry",
        "Whitening Veneers /",
        "Crowns Gingival Contouring",
        "Tooth Reshaping",
        "Diastema Closure",
        "Composite reconstruction",
      ],
    },
    {
      id: "hair_medicine",
      number: 5,
      label: "HAIR MEDICINE",
      items: [
        "PRP for Hair",
        "Hair Mesotherapy",
        "Hydrafacial Scalp",
        "Hair Bleaching",
      ],
    },
    {
      id: "muscle_tone_ems",
      number: 6,
      label: "MUSCLE TONE & EMSFacial Muscle Stimulation",
      items: [
        "EM Sculpt (Face)",
        "EM Sculpt (Body)",
        "Sport Coaching with EMS",
        "Muscle Stimulation",
      ],
    },
    {
      id: "slimming_body_contouring",
      number: 7,
      label: "SLIMMING & BODY CONTOURING",
      items: [
        "Lypolitic Double Chin Removal",
        "Cryolipolysis Injection",
        "Lipolysis (Body)",
        "Weight Loss Medication",
        "Consultation Weight Loss",
        "Diet Consultation",
        "Body Composition Analysis",
        "Diet Program Consultation",
        "Nutrition Program",
      ],
    },
    {
      id: "iv_therapy",
      number: 8,
      label: "IV THERAPY",
      items: ["IV Therapy"],
    },
    {
      id: "wellness_drainage",
      number: 9,
      label: "WELLNESS & DRAINAGE",
      items: [
        "Lymphatic Drainage",
        "Lymphatic Drainage (Legs)",
        "Sclerotherapy",
        "Infrared Sauna",
        "Wellness Analysis",
      ],
    },
    {
      id: "surgical_face",
      number: 10,
      label: "SURGICAL — FACE",
      items: [
        "Mini facelift",
        "Midface lift",
        "Facelift",
        "Temporal lift",
        "ponytail lift",
        "Canthopexy",
        "cat eye surgery",
        "Brow Lift",
        "Upper Blepharoplasty",
        "Lower Blepharoplasty",
        "Rhinoplasty",
        "Ultrasonic Rhinoplasty",
        "Revision Rhinoplasty",
        "Genioplasty",
        "Otoplasty",
        "Lip Lift / Bullhorn Lip Lift",
        "Neck Lift",
        "Lower face and neck skin tightening",
        "Facial Lipofilling (Tear Trough)",
        "Facial Lipofilling (Lips)",
        "Facial Lipofilling (Cheeks)",
        "Facial Feminization Surgery",
        "Buccal Fat Removal / Bichectomy",
      ],
    },
    {
      id: "surgical_body",
      number: 11,
      label: "SURGICAL — BODY",
      items: [
        "Liposuction (Abdomen)",
        "Liposuction (Arms)",
        "Liposuction (Thighs)",
        "Liposuction (Neck)",
        "Liposuction (Other / Knees)",
        "Liposuction (Genitals)",
        "Liposuction (Buttocks)",
        "Body Lift",
        "Arm Lift (Brachioplasty)",
        "Thigh Lift Brazilian Butt Lift / BBL",
        "Buttocks Augmentation,Penis Enlargement",
        "G-Spot Augmentation",
        "Hymenoplasty",
        "Mons Pubis Liposuction",
        "Nymphoplasty / Labiaplasty",
        "Penoplasty",
        "Vaginoplasty",
        "Correction of Breast Asymmetry",
        "Breast Augmentation",
        "Breast Augmentation (Lipofilling)",
        "Breast Reduction",
        "Breast Implant Replacement",
        "Breast Implant Removal",
        "Breast Lifting / Mastopexy",
        "Inverted Nipple Correction",
        "Breast Reconstruction",
        "Abdominoplasty / Tummy Tuck",
        "Abdominal Liposculpture",
        "Liposuction for Lipedema",
        "Forefoot Aesthetic Surgery",
        "Hallux Valgus Surgery",
        "Hammer Toe Surgery",
        "Rib Remodeling / Rib Removal",
        "Circumcision",
        "Perineoplasty",
      ],
    },
    {
      id: "hair_medicine_surgical",
      number: 12,
      label: "HAIR MEDICINE",
      items: [
        "Forehead Reduction",
        "Hairline Lowering",
        "Hair Transplantation",
      ],
    },
  ],

  subzones: {
    faceAndGeneralAreas: {
      label: "Face & General Areas",
      items: [
        "Cheekbones",
        "Cheeks",
        "Chin",
        "Crow’s Feet",
        "Décolletage",
        "Ears",
        "Eyebrows",
        "Eyelids",
        "Forehead",
        "Glabella",
        "Hairs",
        "Jawline",
        "Jowls",
        "Lips",
        "Nasolabial Folds",
        "Neck",
        "Nose",
        "Overall Skin",
        "Perioral Area (upper lip)",
        "Temples",
        "Tear Trough",
        "Teeth",
      ],
    },
    bodySubzones: {
      label: "Body Subzones",
      items: [
        "Abdomen (Belly)",
        "Arms",
        "Breasts",
        "Buttocks",
        "Feet",
        "Genitals",
        "Hands",
        "Knees",
        "Legs",
        "Neck",
        "Other",
        "Thighs",
        "Waist",
      ],
    },
  },
} as const;